# Generated by Django 5.0.8 on 2024-08-09 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("calories_per_100g", models.FloatField()),
                ("protein_per_100g", models.FloatField()),
                ("total_carbs_per_100g", models.FloatField()),
                ("fiber_per_100g", models.FloatField(default=0)),
                ("sugars_per_100g", models.FloatField(default=0)),
                ("total_fat_per_100g", models.FloatField()),
                ("saturated_fat_per_100g", models.FloatField(default=0)),
                ("trans_fat_per_100g", models.FloatField(default=0)),
                ("sodium_per_100g", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserFoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("gram", "gram(s)"),
                            ("ml", "ml(s)"),
                            ("serving", "serving(s)"),
                            ("item", "item(s)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("serving_size", models.IntegerField(default=0)),
                ("total_calories", models.FloatField(default=0)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "breakfast"),
                            ("lunch", "lunch"),
                            ("dinner", "dinner"),
                            ("snack", "snack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal.fooditem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
