# Generated by Django 5.0.8 on 2024-08-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="userfoodentry",
            options={"ordering": ["meal_time"]},
        ),
        migrations.RenameField(
            model_name="userfoodentry",
            old_name="meal",
            new_name="meal_time",
        ),
        migrations.RenameField(
            model_name="userfoodentry",
            old_name="serving_size",
            new_name="quantity",
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("gram", "gram(s)"),
                            ("ml", "ml(s)"),
                            ("serving", "serving(s)"),
                            ("item", "item(s)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal.fooditem"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="meal.RecipeIngredient", to="meal.fooditem"
            ),
        ),
    ]
