# Generated by Django 5.0.8 on 2024-08-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0002_recipe_alter_userfoodentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfoodentry",
            options={},
        ),
        migrations.AlterField(
            model_name="userfoodentry",
            name="unit",
            field=models.CharField(
                choices=[("gram", "gram(s)"), ("ml", "ml(s)")], max_length=20
            ),
        ),
    ]
