# Generated by Django 5.0.8 on 2024-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0003_alter_userfoodentry_options_alter_userfoodentry_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="userfoodentry",
            name="item",
        ),
        migrations.RemoveField(
            model_name="userfoodentry",
            name="unit",
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="food_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="serving_description",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="serving_id",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_calcium",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_carbs",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_cholesterol",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_fats",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_fibers",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_iron",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_monounsaturated_fat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_polyunsaturated_fat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_potassium",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_proteins",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_saturated_fat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_sodium",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_sugar",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_vitamin_a",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="total_vitamin_c",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userfoodentry",
            name="quantity",
            field=models.FloatField(default=1),
        ),
        migrations.DeleteModel(
            name="FoodItem",
        ),
    ]
