# Generated by Django 5.0.8 on 2024-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0004_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfoodentry",
            name="food_id",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userfoodentry",
            name="meal_time",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                ],
                max_length=20,
            ),
        ),
    ]
