# Generated by Django 5.0.8 on 2024-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0005_userfoodentry_food_id_alter_userfoodentry_meal_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfoodentry",
            name="food_id",
        ),
        migrations.AddField(
            model_name="userfoodentry",
            name="serving_choices",
            field=models.CharField(default="", max_length=250),
        ),
    ]
