# Generated by Django 5.0.8 on 2024-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0006_remove_userfoodentry_food_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoodentry",
            name="total_calories",
            field=models.IntegerField(default=0),
        ),
    ]
