# Generated by Django 5.0.8 on 2024-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0007_alter_userfoodentry_total_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoodentry",
            name="serving_choices",
            field=models.CharField(default="", max_length=300),
        ),
    ]
