# Generated by Django 5.0.8 on 2024-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0008_alter_userfoodentry_serving_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfoodentry",
            name="serving_choices",
            field=models.CharField(default="", max_length=500),
        ),
    ]
