# Generated by Django 5.0.8 on 2024-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0009_alter_userfoodentry_serving_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[("gram", "gram(s)"), ("ml", "ml(s)"), ("item", "item(s)")],
                max_length=20,
            ),
        ),
    ]
