# Generated by Django 5.0.8 on 2024-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0010_alter_recipeingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfoodentry",
            name="food_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
