# Generated by Django 5.0.8 on 2024-08-26 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0011_userfoodentry_food_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfoodentry",
            name="serving_choices",
        ),
    ]
