# Generated by Django 5.0.8 on 2024-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0012_remove_userfoodentry_serving_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfoodentry",
            name="serving_choices",
            field=models.CharField(default="", max_length=500),
        ),
    ]
