# Generated by Django 5.0.8 on 2024-08-26 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0013_userfoodentry_serving_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfoodentry",
            name="serving_choices",
        ),
    ]
