# Generated by Django 5.0.8 on 2024-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0014_remove_userfoodentry_serving_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeEntry",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("nutritions_per_serving", models.TextField()),
                ("ingredients", models.TextField()),
                ("other_nutritions_per_serving", models.TextField()),
                ("serving_size", models.FloatField()),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="recipe",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
    ]
