# Generated by Django 5.0.8 on 2024-09-11 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0015_recipeentry_remove_recipeingredient_recipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeentry",
            name="other_nutritions_per_serving",
        ),
    ]
