# Generated by Django 5.0.8 on 2024-09-11 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0016_remove_recipeentry_other_nutritions_per_serving"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeEntry",
        ),
    ]
