# Generated by Django 5.0.8 on 2024-08-09 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserExercise",
            new_name="UserExerciseEntry",
        ),
    ]
