# Generated by Django 5.0.8 on 2024-08-20 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0002_rename_userexercise_userexerciseentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userexerciseentry",
            options={"ordering": ("date",)},
        ),
        migrations.RenameField(
            model_name="userexerciseentry",
            old_name="date_performed",
            new_name="date",
        ),
    ]
