# Generated by Django 5.0.8 on 2024-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0003_alter_userexerciseentry_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userexerciseentry",
            name="exercise",
        ),
        migrations.AddField(
            model_name="userexerciseentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("cardio", "Cardio"),
                    ("strength", "Strength Training"),
                    ("flexibility", "Flexibility"),
                ],
                default="none",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userexerciseentry",
            name="name",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userexerciseentry",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
    ]
