# Generated by Django 5.0.8 on 2024-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0004_remove_userexerciseentry_exercise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("MET_value", models.IntegerField(default=0)),
            ],
        ),
    ]
