# Generated by Django 5.0.8 on 2024-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0005_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="MET_value",
            field=models.FloatField(default=0),
        ),
    ]
