# Generated by Django 5.0.8 on 2024-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0006_alter_exercise_met_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="userexerciseentry",
            name="is_manual",
            field=models.BooleanField(default=True),
        ),
    ]
