# Generated by Django 5.0.8 on 2024-09-02 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0007_alter_exercise_options_userexerciseentry_is_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexerciseentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
