# Generated by Django 5.0.8 on 2024-09-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0008_alter_userexerciseentry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userexerciseentry",
            name="is_manual",
        ),
        migrations.AddField(
            model_name="userexerciseentry",
            name="exercise",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercise.exercise",
            ),
        ),
    ]
