# Generated by Django 5.0.8 on 2024-09-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0010_alter_userexerciseentry_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexerciseentry",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercise.exercise",
            ),
        ),
    ]
