# Generated by Django 5.0.8 on 2024-08-09 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Name", max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("goal_weight", models.IntegerField()),
                ("height", models.IntegerField()),
                ("age", models.IntegerField()),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("health", "Healthier Lifestyle"),
                            ("anxiety", "Manage Anxiety"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (little or no exercise)"),
                            (
                                "light",
                                "Lightly active (light exercise/sports 1-3 days/week)",
                            ),
                            (
                                "moderate",
                                "Moderately active (moderate exercise/sports 3-5 days/week)",
                            ),
                            ("active", "Active (hard exercise/sports 6-7 days a week)"),
                            (
                                "very_active",
                                "Very active (very hard exercise/sports & physical job)",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
