# Generated by Django 5.0.8 on 2024-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "Sedentary (little or no exercise)"),
                    ("light", "Lightly active (light exercise 1-3 days a week)"),
                    (
                        "moderate",
                        "Moderately active (moderate exercise 3-5 days a week)",
                    ),
                    ("active", "Active (hard exercise 6-7 days a week)"),
                    (
                        "very_active",
                        "Very active (very hard exercise/sports & physical job)",
                    ),
                ],
                max_length=100,
            ),
        ),
    ]
