# Generated by Django 5.0.8 on 2024-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_activity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="daily_goal_calories_to_burn",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="daily_needed_calories",
            field=models.IntegerField(default=0),
        ),
    ]
