# Generated by Django 5.0.8 on 2024-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile_daily_goal_calories_to_burn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="weekly_weight_gain_or_loss_goal",
            field=models.FloatField(default=0.5),
        ),
    ]
