# Generated by Django 5.0.8 on 2024-08-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_profile_weekly_weight_gain_or_loss_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="days_until_goal_reached",
            field=models.IntegerField(default=0),
        ),
    ]
