# Generated by Django 5.0.8 on 2024-08-23 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_weighthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weighthistory",
            name="date_logged",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
