# Generated by Django 5.0.8 on 2024-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_weighthistory_date_logged"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calorie_warning",
            field=models.BooleanField(default=False),
        ),
    ]
