# Generated by Django 5.0.8 on 2024-09-03 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_profile_calorie_warning"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="days_until_goal_reached",
            new_name="weeks_until_goal_reached",
        ),
    ]
