# Generated by Django 5.0.8 on 2024-09-06 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user",
            "0009_rename_days_until_goal_reached_profile_weeks_until_goal_reached",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="calorie_warning",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="daily_needed_calories",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="weeks_until_goal_reached",
        ),
    ]
