# Generated by Django 5.0.8 on 2024-09-09 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_profile_calorie_warning_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="daily_goal_calories_to_burn",
        ),
    ]
